### ISSUE TITLE
Firefox extension doesn't seem to work

### ISSUE THREAD

**Issue by ADeeds** [hieupham7127/golinks#17]
Hi, I installed version .2 of the extension from the FF web store, on Firefox version 80.

It doesn't seem like the extension is working properly. I can create a shortcut in the extension you like go/ex that goes to example.com. But actually typing go/ex in the address bar just executes a query for "go/ex" in my default search engine.

**Comment by hieupham7127** [comment]
@ADeeds thanks for reporting the issue. It seems like many people also ran into this problem. 

One possible solution that we found out is to try `http://go/ex` because the browser thought that `go/ex` is `https://go/ex`.  In the mean time, we will try to fix fix this asap.
